name: GoldmanNPC
main: lee.code.npc.GoldmanNPC
version: ${project.version}
api-version: 1.19
author: Lee
depend: [RedisCache]
commands:
  npc:
    description: Main plugin command.
    permission: npc.command.use